environment          = "dev"
project_name         = "oyd-project"
region               = "us-east-1"
app_bucket_prefix    = "app-assets"
db_username          = "admin"
vpc_cidr             = "10.0.0.0/16"
public_subnet_cidrs  = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs = ["10.0.11.0/24", "10.0.12.0/24"]
availability_zones   = ["us-east-1a", "us-east-1b"]
single_nat_gateway   = true
health_check_path    = "/"
