name: Terraform Destroy

# ─── SOLO MANUAL ──────────────────────────────────────────────────────────────
# Este workflow NUNCA corre automáticamente.
# Solo se dispara desde Actions → Terraform Destroy → Run workflow.
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Ambiente a destruir (dev o staging)"
        required: true
        type: choice
        options:
          - dev
          - staging

jobs:
  terraform-destroy-dev:
    name: Terraform Destroy — dev
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'dev'
    environment: dev

    permissions:
      contents: read
      id-token: write  # requerido para OIDC token exchange

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~> 1.8"

      - name: Configure AWS Credentials — OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CI_ROLE_ARN }}
          aws-region:     ${{ secrets.AWS_REGION }}

      - name: Confirm Destroy Target
        run: |
          echo "Destroying environment: dev"

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config=envs/dev/backend-dev.hcl
        working-directory: infra/

      - name: Terraform Destroy
        env:
          TF_VAR_db_password: ${{ secrets.DEV_DB_PASSWORD }}
        run: |
          terraform destroy \
            -var-file=envs/dev/dev.tfvars \
            -auto-approve
        working-directory: infra/

  terraform-destroy-staging:
    name: Terraform Destroy — staging
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'staging'
    environment: staging

    permissions:
      contents: read
      id-token: write  # requerido para OIDC token exchange

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~> 1.8"

      - name: Configure AWS Credentials — OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CI_ROLE_ARN }}
          aws-region:     ${{ secrets.AWS_REGION }}

      - name: Confirm Destroy Target
        run: |
            echo "Destroying environment: staging"
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config=envs/staging/backend-staging.hcl
        working-directory: infra/

      - name: Terraform Destroy
        env:
          TF_VAR_db_password: ${{ secrets.STAGING_DB_PASSWORD }}
        run: |
          terraform destroy \
            -var-file=envs/staging/staging.tfvars \
            -auto-approve
        working-directory: infra/